let state = {
    selfDelivery: null,
    stockDeliveryPickup: false,
    suggestedPostalOffice: false,
    paymentProvider: false,
    signatureHash: false,
    gridCatalog: false,
    lastTwoYearsInfo: false,
    informationPosts: false,
    productsLoaded: false,
    closeListener: false,
    customerIndex: false,
    deliveryType: false,
    cardPayment: false,
    pickUpPoint: false,
    orderPaid: false,
    aboutData: false,
    orders: false,
    user: false,
    cart: false,
    filteredProducts: [],
    searchProducts: [],
    viewedProducts: [],
    modelFilters: [],
    brandFilters: [],
    typeFilters: [],
    products: [],
    customerAdress: {},
    deliveryAdress: {},
    urikValidation: {},
    singleProduct: {},
    uriksData: {},
    order: {},
    usersFIO: '',
    cartStep: 0,
    catalogPerPage: 16,
}

export default state;
